[phases.setup]
nixPkgs = ["nodejs_20", "postgresql"]

[phases.install]
cmds = ["npm ci --include=dev || npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "concurrently -k -s first -n api,web -c green,blue \"API_PORT=3001 node server.js\" \"next start -p $PORT\""
