[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[build.nixpacksConfig]
packageManager = "npm"

[deploy]
startCommand = "node start.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
timeout = 100
interval = 30
